# File: azure-pipelines.yml
# Build Name / Format
name: PowerAppsTestAutomation-$(date:yyyyMMdd)$(rev:.r)

parameters:
 - name: image
   displayName: Pool Image
   type: string
   # See https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/hosted.md#use-a-microsoft-hosted-agent for more pool types
   default: windows-latest
   values:
   - windows-latest
   - vs2017-win2016
   - windows-2019
 - name: BrowserType
   displayName: Browser Type
   type: string
   default: All
   values:
   - Chrome
   - Firefox
   - All
 - name: LoginMethod
   displayName: Login Type # See: https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/user-account-management
   type: string
   default: CloudIdentity
   values:
   - CloudIdentity # Uses the default Office 365 Sign-In Service for authentication
   - FederatedIdentity # Uses a Custom Login Action method using AD FS 2.0 or other Security Token Services for authentication. Custom code is required.
   - PassThrough # Federated login scenario where the provided user credential is automatically logged in, requires special agent configurations

trigger:
   - none

jobs:
- job: "PowerAppsTestFrameworkAutomation"
  pool:
    vmImage: ${{ parameters.image }}
    demands:
    - msbuild
    - visualstudio
    - vstest
  variables:
  - name: PortalUrl
    value: https://make.powerapps.com
    # Browser PrivateMode usage (true/false)
  - name: PrivateMode
    value: true
    # FileName where TestAutomationURLs are stored in JSON format
  - name: TestUrlFileName 
    value: tests.json

  steps:
  - checkout: self
  #- checkout: PowerAppsTestAutomation
  #- template: localsteps.yml # Provide optional local YAML template here
  - bash: |
      echo "hello world"
      echo "{\"TestURLs\": [\"https://apps.powerapps.com/play/{appId}?tenantId={tenantId}&__PATestCaseId={testCaseId}\]}" >> tests.json
      dir
  
  - template: frameworksteps.yml
    parameters:
      OnlineUsername: $(OnlineUsername)
      OnlinePassword: $(OnlinePassword)
      OnlineUrl: $(PortalUrl)
      BrowserType: ${{ parameters.BrowserType }}
      # File location format is /s/TeamProjectName/FilePathToTestAutomationURLs.json
      TestAutomationURLFilePath: $(Build.SourcesDirectory)\$(TestUrlFileName)
      UsePrivateMode: $(PrivateMode)
      LoginMethod: ${{ parameters.LoginMethod }}
      RepositoryName: $(Build.SourcesDirectory)